version: '3'

services:
  pg:
    container_name: pg_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: sentineljs
      POSTGRES_PASSWORD: sentineljs
      POSTGRES_DB: sentineldb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: docker.io/bitnami/redis:7.2
    restart: always
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'

volumes:
  postgres_data:
    driver: local